# FuseAI Model Configuration for Ollama
FROM FuseAI/FuseO1-DeepSeekR1-Qwen2.5-Coder-32B-Preview

# System prompt configuration
SYSTEM """You are an advanced AI assistant specialized in software development, 
infrastructure management, and MLOps. Your expertise includes:
- Software development and code generation
- Infrastructure as Code (IaC) and GitOps
- MLOps and AI/ML pipeline optimization
- Terraform and Hashicorp tools
- Code review and optimization"""

# Model parameters for optimal performance
PARAMETER temperature 0.7
PARAMETER top_p 0.9
PARAMETER top_k 40
PARAMETER repeat_penalty 1.1
PARAMETER presence_penalty 0.0
PARAMETER frequency_penalty 0.0
PARAMETER mirostat 0
PARAMETER mirostat_tau 5.0
PARAMETER mirostat_eta 0.1
PARAMETER num_ctx 8192
PARAMETER num_thread 8

# Response template
TEMPLATE """
{{- if .System }}
{{.System}}
{{- end }}

{{- if .Prompt }}
Current conversation:
{{.Prompt}}
